name: .NET Playwright CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chromium ]

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        working-directory: PlaywrightTests
        run: dotnet restore

      - name: Build (Release)
        working-directory: PlaywrightTests
        run: dotnet build --configuration Release --no-restore

      # تثبيت متصفحات Playwright على Ubuntu عبر playwright.sh
      - name: Install Playwright browsers
        run: |
          set -eux
          dotnet build PlaywrightTests/PlaywrightTests.csproj -c Release --no-restore
          script_path=$(find PlaywrightTests -type f -name "playwright.sh" | head -n 1)
          if [ -z "$script_path" ]; then
            echo "playwright.sh not found"; exit 1
          fi
          bash "$script_path" install --with-deps

      - name: Run tests
        working-directory: PlaywrightTests
        env:
          BROWSER: ${{ matrix.browser }}
        run: |
          mkdir -p artifacts/traces artifacts/screenshots allure-results || true
          dotnet test PlaywrightTests.csproj \
            --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            --results-directory artifacts \
            --no-build

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.browser }}
          path: |
            PlaywrightTests/artifacts/**
            PlaywrightTests/allure-results/**
          if-no-files-found: ignore
