name: .NET Playwright CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chromium ]   # add firefox, webkit later if you like

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          # dotnet-quality: "preview"   # uncomment only if you target a preview SDK

      - name: Dotnet info
        run: dotnet --info

      - name: Restore
        working-directory: PlaywrightTests
        run: dotnet restore

      - name: Build (Release)
        working-directory: PlaywrightTests
        run: dotnet build --configuration Release --no-restore

      - name: Setup Node.js (for Playwright browsers)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests (NUnit + Playwright)
        working-directory: PlaywrightTests
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: "true"           # force headless on CI
          # BASE_URL: ${{ secrets.BASE_URL }}   # optional: provide via repo secrets
        run: |
          mkdir -p artifacts/traces artifacts/screenshots allure-results || true
          dotnet test PlaywrightTests.csproj \
            --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            --logger "console;verbosity=detailed" \
            --results-directory artifacts \
            --no-build

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.browser }}
          path: |
            PlaywrightTests/artifacts/**
            PlaywrightTests/allure-results/**
          if-no-files-found: ignore

      - name: Publish TRX summary
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: NUnit Results
          path: PlaywrightTests/artifacts/*.trx
          reporter: dotnet-trx
