name: dotnet-playwright-ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # نشغّل أوامر الـ dotnet من مجلد المشروع
    defaults:
      run:
        shell: bash
        working-directory: PlaywrightTests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore  # نحن داخل PlaywrightTests لذا لا نحتاج مسار .sln

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      # تثبيت متصفحات Playwright (لينكس يحتاج --with-deps)
      - name: Install Playwright browsers
        shell: pwsh
        run: ./bin/Release/net9.0/playwright.ps1 install --with-deps

      - name: Test
        run: dotnet test -c Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory artifacts

      # ارفع النتائج حتى لو فشل الاختبار
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: PlaywrightTests/artifacts
