name: dotnet-playwright-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true                 # بيئة CI, بعض الأكواد تعتمد عليه
      PW_TIMEOUT: 45000        # (اختياري) مهلة افتراضية 45s لو كنتِ تقرئيها بالكود

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      # يثبت متصفحات Playwright اللازمة للتشغيل في Linux
      - name: Install Playwright browsers
        shell: pwsh
        run: |
          $ps1 = "$(Get-ChildItem -Path ./PlaywrightTests/bin/Release -Recurse -Filter playwright.ps1 | Select-Object -First 1).FullName"
          if (-not $ps1) { throw "playwright.ps1 not found under ./PlaywrightTests/bin/Release" }
          & $ps1 install --with-deps

      # (اختياري للتشخيص) اطبعي موقع TestBase.cs إن احتجتي
      - name: Locate TestBase.cs (debug)
        run: |
          echo "Searching for TestBase.cs …"
          git ls-files | grep -i 'TestBase.cs' || true

      - name: Test
        run: |
          dotnet test -c Release --no-build \
            --logger "trx;LogFileName=test_results.trx" \
            --results-directory PlaywrightTests/artifacts

      # ارفعي نتائج التست (حتى لو فشل) — TRX + أي traces/تقارير لو مشغلة من الكود
      - name: Upload test results (TRX + traces if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            PlaywrightTests/artifacts
            **/trace*.zip
            **/playwright-report/**/*
          if-no-files-found: warn

      # عند الفشل اعرضي شجرة الملفات القريبة للمساعدة
      - name: Dump tree on failure
        if: failure()
        run: |
          echo "=== repo tree (top 3 levels) ==="
          find . -maxdepth 3 -type d -print
