name: dotnet-playwright-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    # كل الأوامر ستعمل داخل مجلد مشروع الاختبارات
    defaults:
      run:
        working-directory: PlaywrightTests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Install Playwright browsers
        run: pwsh ./bin/Release/net9.0/playwright.ps1 install --with-deps
        
      - name: Print TestBase.cs content
        run: cat PlaywrightTests/Utils/TestBase.cs
        
      - name: Test
        run: dotnet test -c Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory artifacts
        env:
          CI: true
          PW_TIMEOUT: 45000  # 45s للعمليات الافتراضية

      - name: Upload test results (TRX + traces if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            PlaywrightTests/artifacts
            PlaywrightTests/bin/**/trace*.zip
            **/playwright-report/**/*
