name: .NET Playwright CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { browser: [chromium] }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }

      - name: Restore
        working-directory: PlaywrightTests
        run: dotnet restore

      - name: Build (Release)
        working-directory: PlaywrightTests
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright browsers
        shell: pwsh
        working-directory: PlaywrightTests
        run: |
          $script = Get-ChildItem -Recurse -Filter playwright.ps1 | Where-Object { $_.FullName -match "bin[/\\]Release[/\\]net" } | Select-Object -First 1
          if (-not $script) { $script = Get-ChildItem -Recurse -Filter playwright.ps1 | Select-Object -First 1 }
          if (-not $script) { throw "playwright.ps1 not found. Did the build complete?" }
          & $script.FullName install --with-deps

      - name: Run tests
        working-directory: PlaywrightTests
        env: { BROWSER: ${{ matrix.browser }} }
        run: |
          mkdir -p artifacts/traces artifacts/screenshots allure-results || true
          dotnet test PlaywrightTests.csproj --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            --results-directory artifacts --no-build

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.browser }}
          path: |
            PlaywrightTests/artifacts/**
            PlaywrightTests/allure-results/**
          if-no-files-found: ignore
