name: .NET Playwright CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chromium ]   # أضيفي firefox, webkit لاحقًا لو رغبتِ

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          include-prerelease: true   # احذفي هذا السطر إذا كنتِ على إصدار GA مستقر

      - name: Show .NET info (diagnostic)
        run: dotnet --info

      - name: Restore
        working-directory: PlaywrightTests
        run: dotnet restore

      - name: Build (Release)
        working-directory: PlaywrightTests
        run: dotnet build --configuration Release --no-restore

      # نثبت المتصفحات عبر Node — يعمل بسلاسة على Ubuntu
      - name: Setup Node.js (for Playwright browsers)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests (NUnit + Playwright)
        working-directory: PlaywrightTests
        env:
          BROWSER: ${{ matrix.browser }}   # استخدميه في TestBase لو حابة تبدّلي المتصفح
        run: |
          mkdir -p artifacts/traces artifacts/screenshots allure-results || true
          dotnet test PlaywrightTests.csproj \
            --configuration Release \
            --logger "trx;LogFileName=test_results.trx" \
            --results-directory artifacts \
            --no-build

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.browser }}
          path: |
            PlaywrightTests/artifacts/**
            PlaywrightTests/allure-results/**
          if-no-files-found: ignore
